version: "3"
include:
  - proxy.yaml

services:
  web:
    image: web:1.0.0
    build:
      dockerfile: Dockerfile.python
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    networks:
        backend:
          ipv4_address: 172.20.0.5
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}

  db:
    image: mysql:8
    restart: on-failure
    networks:
        backend:
          ipv4_address: 172.20.0.10
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD']
      interval: 5s
      retries: 120